In [90]:
# Imports

from keras.models import *
from keras.layers import *
from keras import Input
from keras import Sequential
from tensorflow import keras

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split

import numpy as np
from keras import metrics
from sklearn.preprocessing import OneHotEncoder, StandardScaler



In [113]:
path = "irisData.txt"

In [114]:
#Load Dataset

data = pd.read_csv(path)


In [115]:
data

x1   x2   x3   x4               y
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [116]:
# Scale all values

X = data.iloc[ : , 0:4 ]

maxNums = X.max()

X['x1'] = X['x1']/maxNums[0]
X['x2'] = X['x2']/maxNums[1]
X['x2'] = X['x3']/maxNums[2]
X['x3'] = X['x4']/maxNums[3]


X

x1        x2    x3   x4
0    0.645570  0.202899  0.08  0.2
1    0.620253  0.202899  0.08  0.2
2    0.594937  0.188406  0.08  0.2
3    0.582278  0.217391  0.08  0.2
4    0.632911  0.202899  0.08  0.2
..        ...       ...   ...  ...
145  0.848101  0.753623  0.92  2.3
146  0.797468  0.724638  0.76  1.9
147  0.822785  0.753623  0.80  2.0
148  0.784810  0.782609  0.92  2.3
149  0.746835  0.739130  0.72  1.8

[150 rows x 4 columns]

In [117]:
# Hot encode the Y values

Y = data.iloc[ : , 4:5 ]

enc = OneHotEncoder()

Y = enc.fit_transform(Y).toarray()

Y = pd.DataFrame(Y)

x_train , x_test , y_train , y_test = train_test_split(X,Y, test_size=0.2, random_state=123)


In [118]:
X

x1        x2    x3   x4
0    0.645570  0.202899  0.08  0.2
1    0.620253  0.202899  0.08  0.2
2    0.594937  0.188406  0.08  0.2
3    0.582278  0.217391  0.08  0.2
4    0.632911  0.202899  0.08  0.2
..        ...       ...   ...  ...
145  0.848101  0.753623  0.92  2.3
146  0.797468  0.724638  0.76  1.9
147  0.822785  0.753623  0.80  2.0
148  0.784810  0.782609  0.92  2.3
149  0.746835  0.739130  0.72  1.8

[150 rows x 4 columns]

In [119]:
Y

0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [120]:
model = Sequential()

model.add( Input(shape=(4,), dtype="float32"   )  )
model.add( Dense(3, activation='sigmoid')  )
model.add( Dense(3, activation='relu')  )
model.add( Dense(3, activation='sigmoid')  )

model.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 12        
Total params: 39
Trainable params: 39
Non-trainable params: 0
_________________________________________________________________


In [130]:
#compile model: add optimizer and Loss

model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['accuracy' , 'Recall' , 'Precision'])

In [139]:
model.fit( x_train, y_train, epochs=10, batch_size=128, validation_split=0.1)

Epoch 1/10
1/1 [==============================] - 0s 59ms/step - loss: 0.9118 - accuracy: 0.8426 - recall: 0.6759 - precision: 0.6186 - val_loss: 0.9421 - val_accuracy: 0.8333 - val_recall: 0.6667 - val_precision: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 24ms/step - loss: 0.9105 - accuracy: 0.8426 - recall: 0.6759 - precision: 0.6186 - val_loss: 0.9411 - val_accuracy: 0.8333 - val_recall: 0.6667 - val_precision: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 24ms/step - loss: 0.9092 - accuracy: 0.8426 - recall: 0.6852 - precision: 0.6218 - val_loss: 0.9400 - val_accuracy: 0.8333 - val_recall: 0.6667 - val_precision: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 24ms/step - loss: 0.9080 - accuracy: 0.8426 - recall: 0.6852 - precision: 0.6218 - val_loss: 0.9389 - val_accuracy: 0.8333 - val_recall: 0.6667 - val_precision: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 24ms/step - loss: 0.9067 - accuracy: 0.8426 - recall: 0.6944 - 

In [140]:
model.get_weights()

[array([[-0.33100888, -0.7456025 , -0.602065  ],
        [ 0.67159873,  1.1907432 ,  0.1563546 ],
        [ 0.038387  ,  0.69843453,  0.5602159 ],
        [ 0.9914924 , -0.42827168, -0.9357059 ]], dtype=float32),
 array([-0.41870344, -0.13644457,  0.4444874 ], dtype=float32),
 array([[ 0.6443411 , -0.6814163 , -0.04843484],
        [ 0.51596314, -0.5263915 ,  0.00461043],
        [-0.76441437,  0.41975355,  1.3502228 ]], dtype=float32),
 array([-0.09996484,  0.        ,  0.00818558], dtype=float32),
 array([[-0.55060947,  0.06462794,  1.3092911 ],
        [ 0.39406085, -0.515888  , -0.05152178],
        [ 0.28533283, -0.51268744, -0.9357582 ]], dtype=float32),
 array([-0.08990777,  0.14776403, -0.20301484], dtype=float32)]

In [141]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 11ms/step - loss: 0.8599 - accuracy: 0.9333 - recall: 0.8333 - precision: 0.6579


[0.8598629832267761,
 0.9333333373069763,
 0.8333333134651184,
 0.6578947305679321]

In [66]:
xvec = np.asarray(x_test.iloc[0])
xvec = np.expand_dims( xvec,0)

yvec = np.asarray(y_test.iloc[0])
yvec = np.expand_dims( yvec,0)

In [67]:
xvec

array([[0.79746835, 0.71014493, 0.6       , 1.5       ]])

In [68]:
yvec

array([[0., 1., 0.]])

In [69]:
result = model.predict(xvec)
result

array([[0.47014922, 0.568176  , 0.57733345]], dtype=float32)

In [84]:
unscaled = [(xvec[0] * maxNums)]
unscaled

[x1    6.300000
 x2    3.124638
 x3    4.140000
 x4    3.750000
 dtype: float64]

In [85]:
x_test

x1        x2    x3   x4
72   0.797468  0.710145  0.60  1.5
112  0.860759  0.797101  0.84  2.1
132  0.810127  0.811594  0.88  2.2
88   0.708861  0.594203  0.52  1.3
37   0.620253  0.217391  0.04  0.1
138  0.759494  0.695652  0.72  1.8
87   0.797468  0.637681  0.52  1.3
42   0.556962  0.188406  0.08  0.2
8    0.556962  0.202899  0.08  0.2
90   0.696203  0.637681  0.48  1.2
141  0.873418  0.739130  0.92  2.3
33   0.696203  0.202899  0.08  0.2
59   0.658228  0.565217  0.56  1.4
116  0.822785  0.797101  0.72  1.8
135  0.974684  0.884058  0.92  2.3
104  0.822785  0.840580  0.88  2.2
36   0.696203  0.188406  0.08  0.2
13   0.544304  0.159420  0.04  0.1
63   0.772152  0.681159  0.56  1.4
45   0.607595  0.202899  0.12  0.3
28   0.658228  0.202899  0.08  0.2
133  0.797468  0.739130  0.60  1.5
24   0.607595  0.275362  0.08  0.2
127  0.772152  0.710145  0.72  1.8
46   0.645570  0.231884  0.08  0.2
20   0.683544  0.246377  0.08  0.2
31   0.683544  0.217391  0.16  0.4
121  0.708861  0.710145  0.80  2.0
117  0.974684  0.971014  0.88  2.2
4    0.632911  0.202899  0.08  0.2

In [86]:
y_test

0    1    2
72   0.0  1.0  0.0
112  0.0  0.0  1.0
132  0.0  0.0  1.0
88   0.0  1.0  0.0
37   1.0  0.0  0.0
138  0.0  0.0  1.0
87   0.0  1.0  0.0
42   1.0  0.0  0.0
8    1.0  0.0  0.0
90   0.0  1.0  0.0
141  0.0  0.0  1.0
33   1.0  0.0  0.0
59   0.0  1.0  0.0
116  0.0  0.0  1.0
135  0.0  0.0  1.0
104  0.0  0.0  1.0
36   1.0  0.0  0.0
13   1.0  0.0  0.0
63   0.0  1.0  0.0
45   1.0  0.0  0.0
28   1.0  0.0  0.0
133  0.0  0.0  1.0
24   1.0  0.0  0.0
127  0.0  0.0  1.0
46   1.0  0.0  0.0
20   1.0  0.0  0.0
31   1.0  0.0  0.0
121  0.0  0.0  1.0
117  0.0  0.0  1.0
4    1.0  0.0  0.0

In [128]:
data.iloc[72]

x1                6.3
x2                2.5
x3                4.9
x4                1.5
y     Iris-versicolor
Name: 72, dtype: object

In [143]:
def get_flower_type(arg1, arg2 , arg3, arg4):
    modelIris = keras.models.load_model('ps1modelIris')

    preVec = [arg1/maxNums[0], arg2/maxNums[1] , arg3/maxNums[2], arg4/maxNums[3]] 
    rVec = np.expand_dims( preVec,0)
        
    result = modelIris.predict(rVec)
        
    tClass = result.max()
    
    if(tClass == result[0][0]):
        
        print('Iris-setosa')
        
    if(tClass == result[0][1]):
        
        print('Iris-versicolor')    
        
    if(tClass == result[0][2]):
        
        print('Iris-virginica')
        
    print(result)

In [144]:
get_flower_type(5.1,3.0,1.7,0.4)

Iris-setosa
[[0.51371646 0.44751924 0.32505676]]


In [142]:
model.save('modelIris')

INFO:tensorflow:Assets written to: ps1modelIris\assets
